stages:
  - build
  - deploy


image: node:10-slim

build:
  stage: build
  script:
  - npm install
  - npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploy to dodsorf.as"
  environment:
    name: wug dodsorf.as
  only:
  - master